"""changing id type

Revision ID: 4439da036fd0
Revises: af93d5b8ca0a
Create Date: 2025-03-30 20:28:03.509123

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '4439da036fd0'
down_revision: Union[str, None] = 'af93d5b8ca0a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_mortgages_id', table_name='mortgages')
    op.drop_table('mortgages')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mortgages',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('credit_score', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('loan_amount', mysql.FLOAT(), nullable=False),
    sa.Column('property_value', mysql.FLOAT(), nullable=False),
    sa.Column('annual_income', mysql.FLOAT(), nullable=False),
    sa.Column('debt_amount', mysql.FLOAT(), nullable=False),
    sa.Column('loan_type', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('property_type', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('credit_rating', mysql.VARCHAR(length=10), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_mortgages_id', 'mortgages', ['id'], unique=False)
    # ### end Alembic commands ###
