"""changing column names

Revision ID: e9550ca576bf
Revises: 4439da036fd0
Create Date: 2025-03-30 20:36:37.095055

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'e9550ca576bf'
down_revision: Union[str, None] = '4439da036fd0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('mortgages')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mortgages',
    sa.Column('id', mysql.CHAR(length=36), nullable=False),
    sa.Column('credit_score', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('loan_amount', mysql.FLOAT(), nullable=False),
    sa.Column('property_value', mysql.FLOAT(), nullable=False),
    sa.Column('annual_income', mysql.FLOAT(), nullable=False),
    sa.Column('debt_amount', mysql.FLOAT(), nullable=False),
    sa.Column('loan_type', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('property_type', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('credit_rating', mysql.VARCHAR(length=10), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
